### ISSUE TITLE
KeyError: 'genome_name'

### ISSUE THREAD

**Issue by palomo11** [snayfach/MIDAS-strains#1]
Hi,

I'm trying to use MIDAS-strains but I have got the following error:
```
Traceback (most recent call last):
  File "/home/namel/scripts/MIDAS_strain/MIDAS-strains/midas_strains.py", line 179, in <module>
    row = [species_id, genome_info[genome_id]['genome_name'], genome_id, ','.join(cluster_to_genomes[genome_id]), obs_abun*tot_abun, obs_abun*tot_reads, obs_abun*tot_depth]
KeyError: 'genome_name'
```

Any idea about what is going on?

I have follow the pipeline described in MIDAS-strains. But I build my own database. midas species and midas genes run without any problem.

Thanks in advance.

**Comment by palomo11** [comment]
I just modified the script and removed the genome_name in that line and in line 187, and run it again, but I got another error:

```
Traceback (most recent call last):
  File "/home/people/name/scripts/MIDAS_strain/MIDAS-strains/midas_strains_new.py", line 171, in <module>
    coefficients, residual = nnls(A=matrix, b=vector)
  File "/home/people/name/.local/lib/python2.7/site-packages/scipy/optimize/nnls.py", line 56, in nnls
    x, rnorm, mode = _nnls.nnls(A, m, n, b, w, zz, index)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```
In 2 of my 24 samples, the strain_freq.tsv file was created but not in the rest. It might be because for a specific species no strain was detected?

```
13. MAG23
reading read-depth (i.e. coverage) of pangenome genes from MIDAS output
  total genes: 4297
clustering reference strains at 90.0% gene content similarity
  total strains: 2, clustered strains: 2
selecting subset of genes found in <=50.0% of reference strains to use for strain estimation
  retained genes: 1653
obtaining initial estimation of strain frequencies
  total strains detected: 0
re-estimating frequencies after removing strains with <10.0% relative frequency
Traceback (most recent call last):
  File "/home/name/scripts/MIDAS_strain/MIDAS-strains/midas_strains_new.py", line 171, in <module>
    coefficients, residual = nnls(A=matrix, b=vector)
  File "/home/people/name/.local/lib/python2.7/site-packages/scipy/optimize/nnls.py", line 56, in nnls
    x, rnorm, mode = _nnls.nnls(A, m, n, b, w, zz, index)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

**Comment by snayfach** [comment]
Thanks for reporting the issue. If you send me your data I can take a look into it.
